name: Format Code

on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Lint & Format
        run: npm run format
      - run: git status
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_HEAD_REF
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'test'

